unified-delay: true
proxy-providers:
 Akun-VPN:
    type: file
    path: "./vpn.yaml"
    health-check:
      enable: true
      url: http://howdy.id/ping.php
      interval: 300
proxy-groups:
- name: VPN
  type: select
 # strategy: consistent-hashing
  use:
  - Akun-VPN
  proxies:
  - DIRECT
- name: Ads
  type: select
  proxies:
  - VPN
  - REJECT
rule-providers:
  Rule_AdBlock:
    type: file
    behavior: domain
    path: "./rule_basicads.yaml"
  Rule_Personalads:
    type: file
    behavior: classical
    path: "./rule_personalads.yaml"
rules:
- RULE-SET,Rule_AdBlock,Ads
- RULE-SET,Rule_Personalads,Ads
- MATCH,VPunified-delay: true
proxy-providers:
 Akun-VPN:
    type: file
    path: "./vpn.yaml"
    health-check:
      enable: true
      url: http://howdy.id/ping.php
      interval: 300
proxy-groups:
- name: VPN
  type: select
 # strategy: consistent-hashing
  use:
  - Akun-VPN
  proxies:
  - DIRECT
- name: Ads
  type: select
  proxies:
  - VPN
  - REJECT
rule-providers:
  Rule_AdBlock:
    type: file
    behavior: domain
    path: "./rule_basicads.yaml"
  Rule_Personalads:
    type: file
    behavior: classical
    path: "./rule_personalads.yaml"
rules:
- RULE-SET,Rule_AdBlock,Ads
- RULE-SET,Rule_Personalads,Ads
- MATCH,VPNcks-port